//A STREAM IS A SEQUENCE OF DATA THAT IS BEING MOVED FROM ONE POINT TO ANOTHER OVER TIME
//EX: STREAM OF DATA OVER THE INTERNET BEING MOVED FROM ONE COMPUTER TO ANOTHER

//PROCESS STREAMS OF DATA IN CHUNKS AS THEY ARRIVE INSTEAD OF WAITING FOR THE ENTIRE DATA TO BE AVAILABLE BEFORE PROCESSING
